import { CampusItem, MatchResult, UserProfile, ClaimVerification } from '../types/retrivo';

export const CURRENT_USER: UserProfile = {
  id: 'usr_current_student_01',
  student_id: 'CS-2024-8841',
  name: 'Samira Patel',
  email: 'samira.patel@campus.edu',
  avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&auto=format&fit=crop&q=80',
  department: 'Computer Science & Engineering',
  phone_number: '+1 (555) 234-8891',
  trust_score: 96,
  created_at: '2024-01-15T09:00:00Z',
};

export const INITIAL_USERS: UserProfile[] = [
  CURRENT_USER,
  {
    id: 'usr_campus_security',
    student_id: 'STAFF-SEC-104',
    name: 'Officer Ramirez (Campus Security)',
    email: 'security.lostfound@campus.edu',
    avatar_url: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    department: 'Campus Safety & Police',
    trust_score: 99,
  },
  {
    id: 'usr_jordan_lee',
    student_id: 'BIO-2023-4210',
    name: 'Jordan Lee',
    email: 'jordan.lee@campus.edu',
    avatar_url: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&auto=format&fit=crop&q=80',
    department: 'Biological Sciences',
    trust_score: 91,
  },
];

export const INITIAL_ITEMS: CampusItem[] = [
  {
    id: 'item_lost_01',
    type: 'lost',
    title: 'Sony WH-1000XM4 Noise Canceling Headphones',
    description: 'Matte black over-ear headphones left behind in a study cubicle. Inside a dark gray zipper case.',
    category: 'electronics',
    campus_location: {
      building: 'Main Library',
      floor_or_room: '2nd Floor Silent Study Area, Desk #34',
      latitude: 37.4275,
      longitude: -122.1697,
    },
    timestamp: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80',
    hidden_clue: 'Small holographic NASA decal stuck under the inner left headband cushion.',
    status: 'open',
    user_id: 'usr_current_student_01',
    created_at: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
  },
  {
    id: 'item_found_01',
    type: 'found',
    title: 'Black Sony Wireless Over-Ear Headphones',
    description: 'Found on desk in 2nd floor library near the science stacks. Turned in to 1st floor help desk.',
    category: 'electronics',
    campus_location: {
      building: 'Main Library',
      floor_or_room: '2nd Floor Stacks / Desk #34',
      latitude: 37.4276,
      longitude: -122.1695,
    },
    timestamp: new Date(Date.now() - 2.5 * 3600 * 1000).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1583394838336-acd977736f90?w=800&auto=format&fit=crop&q=80',
    hidden_clue: 'Holographic NASA decal inside left headband cushion.',
    status: 'open',
    user_id: 'usr_campus_security',
    created_at: new Date(Date.now() - 2.5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'item_lost_02',
    type: 'lost',
    title: 'Cobalt Blue Hydro Flask 32oz',
    description: 'Wide-mouth insulated bottle with a flex cap. Extremely sentimental travel stickers.',
    category: 'accessories',
    campus_location: {
      building: 'Student Recreation Center',
      floor_or_room: 'Court 2 bleachers',
      latitude: 37.4261,
      longitude: -122.1664,
    },
    timestamp: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80',
    hidden_clue: 'Small dent on bottom corner, plus a scratched Yosemite National Park sticker.',
    status: 'under_verification',
    user_id: 'usr_jordan_lee',
    created_at: new Date(Date.now() - 14 * 3600 * 1000).toISOString(),
  },
  {
    id: 'item_found_02',
    type: 'found',
    title: 'Navy Blue Metal Water Bottle with Stickers',
    description: 'Found under the bleachers after 5 PM intramural volleyball games.',
    category: 'accessories',
    campus_location: {
      building: 'Student Recreation Center',
      floor_or_room: 'Basketball Court 2 Bleachers',
      latitude: 37.4262,
      longitude: -122.1663,
    },
    timestamp: new Date(Date.now() - 13.5 * 3600 * 1000).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?w=800&auto=format&fit=crop&q=80',
    hidden_clue: 'Bottom dent + Yosemite decal.',
    status: 'under_verification',
    user_id: 'usr_current_student_01',
    created_at: new Date(Date.now() - 13.5 * 3600 * 1000).toISOString(),
  },
  {
    id: 'item_found_03',
    type: 'found',
    title: 'Campus ID Card + Dorm Lanyard',
    description: 'Student ID card in a blue lanyard with dorm room key attached.',
    category: 'identification',
    campus_location: {
      building: 'Dining Commons',
      floor_or_room: 'Front entryway turnstiles',
      latitude: 37.425,
      longitude: -122.17,
    },
    timestamp: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=800&auto=format&fit=crop&q=80',
    hidden_clue: 'Red dorm fob number 408 stamped on reverse.',
    status: 'open',
    user_id: 'usr_campus_security',
    created_at: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
  },
  {
    id: 'item_lost_03',
    type: 'lost',
    title: 'TI-84 Plus CE Calculator (Mint Green)',
    description: 'Graphing calculator left behind after Calculus midterm. Has name written in silver sharpie on back.',
    category: 'stationery_books',
    campus_location: {
      building: 'Mathematics Hall',
      floor_or_room: 'Room 380 Lecture Hall',
      latitude: 37.428,
      longitude: -122.168,
    },
    timestamp: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    image_url: 'https://images.unsplash.com/photo-1594980596870-8aa52a78d8cd?w=800&auto=format&fit=crop&q=80',
    hidden_clue: 'Custom periodic table sticker inside the sliding cover.',
    status: 'open',
    user_id: 'usr_current_student_01',
    created_at: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_MATCHES: MatchResult[] = [
  {
    lost_item_id: 'item_lost_01',
    found_item_id: 'item_found_01',
    match_score: 9.6,
    breakdown: {
      text_score: 0.96,
      image_score: 0.98,
      location_score: 0.99,
      time_score: 0.92,
    },
    recommended_action: 'notify_owner',
    matched_at: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    lost_item_id: 'item_lost_02',
    found_item_id: 'item_found_02',
    match_score: 9.3,
    breakdown: {
      text_score: 0.91,
      image_score: 0.94,
      location_score: 0.98,
      time_score: 0.93,
    },
    recommended_action: 'notify_owner',
    matched_at: new Date(Date.now() - 12 * 3600 * 1000).toISOString(),
  },
];

export const INITIAL_CLAIMS: ClaimVerification[] = [
  {
    id: 'claim_01',
    item_id: 'item_found_02',
    claimant_id: 'usr_jordan_lee',
    proof_answer: 'It has a small dent on the bottom rim and a faded Yosemite National Park sticker.',
    status: 'verified',
    handover_code: '849-216',
    handover_confirmed_at: null,
    created_at: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
  },
];

